### PR TITLE
Add AppVerifier to CI

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
*Description of changes:*

Adds AppVerifier to run alongside tests for `aws-checksums` to ensure proper Win32 API usage.

________

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by graebm — APPROVED** [review]

**Comment by ck740** [comment]
Update

**Comment by ck740** [comment]
Solve

**Comment by ck740** [comment]
652

**Comment by ck740** [comment]
#58

**Comment by ck740** [comment]
AppVerifier

**Pull request merged**
