### PR TITLE
Change +c and +d output registers to +g.

### PR DESCRIPTION
**Pull request by egorpugin**
Fixes https://github.com/awslabs/aws-checksums/issues/8

### CODE REVIEW

**Comment by egorpugin** [comment]
Clang-6 build failed, but locally I able to build that file with clang-6 and clang-7.
Also clang-3 build on CI is fine too.
Maybe you have some issues with clang-6 CI build configuration?

**Comment by JonathanHenson** [comment]
Run the format-check.sh script and it will tell you which fails.

**Comment by egorpugin** [comment]
It says:
```
$ ./format-check.sh 
source/arm/cpuid_arm.c failed clang-format check.
```

But I did not touch it. :)

**Comment by JonathanHenson** [comment]
Clang-format -i source/arm/cpuid_arm.c

**Comment by JonathanHenson** [comment]
I'm going to merge your work into this one, since this makes sure the asm is actually tested in the CI and it adds gcc-8 to the test runs.

https://github.com/awslabs/aws-checksums/pull/10

**Comment by egorpugin** [comment]
Ok, thank you.
Feel free to close this.

**Comment by JonathanHenson** [comment]
unfortunately, this code ends up being in correct in Debug build. Did the tests pass when you used this flag?

**Comment by egorpugin** [comment]
I did not test it.
I assumed something incorrect in such changes, so I asked first.
Maybe it is gcc bug? Why same thing does not work with `-O`?

**Comment by JonathanHenson** [comment]
The reason we don't trust GCC in this code to pick the registers for us, is it's frequently wrong. It's correct on optimized builds and wrong on debug builds. This is probably for the same reason it can't pick a register in the debug builds. Closing PR for now.

**Pull request closed without merging**
